production:
  dragon:
    price: 0
    price_staff: 0
    level: 1
    clothes:
      armory:
        count: 5
        color: 0xdee1f0
#      fon:
#        by_names: ['stone']
#        color: 0xFFFFFF

test:
  dragon:
    price: 0
    price_staff: 0
    level: 1
    clothes:
      armory:
        count: 5
        color: 0xdee1f0

development:
   dragon:
    price: 0
    price_staff: 0
    level: 1
    clothes:
      armory:
        count: 5
        color: 0xdee1f0